version: '3'

services:

  db-falabella:
    build: ./postgres
    image: db-falabella:1.0
    ports:
      - 15432:5432
    networks:
      - database_network
    volumes:
      - database_data_volume:/var/lib/postgresql/data

networks:

  database_network:
    driver: bridge

volumes:
  database_data_volume: